# Generated by Django 4.0.6 on 2022-08-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_apps', '0004_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='potho_author',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='potho_book',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
